o: test.c /home/bonbonbaron/hack/jollybean/build/data.o
	gcc test.c /home/bonbonbaron/hack/jollybean/build/data.o -I/home/bonbonbaron/hack/jollybean/src/include -o $@

/home/bonbonbaron/hack/jollybean/build/data.o: /home/bonbonbaron/hack/jollybean/src/data.c
	make -C /home/bonbonbaron/hack/jollybean
