#include "body.h"

/* 
 * Passed-in arguments: name of bod[y|ies].
 */
int main(int argc, char ** argv) {
  memIni( 1000000, MAIN );
  memIni( 1000000, TEMP );
  AnimJsonData *animP = NULL;

  // Verbose 
  U8 verbose = 0;

  // Write all the bodies.
  for (U32 i = 1; i < argc; ++i) {
    if (!strcmp(argv[i], "-v")) {
      verbose = 1;
      continue;
    }
    // Animation
    anim(argv[i], verbose, &animP);
    // Colormap and Color palette (autogenerated)
    img(argv[i], animP, verbose);
    // Collision
    // coll(argv[i], 0, animP, verbose);
  }
}
