#!/bin/bash

source ./scripts/ini
source ./scripts/sys
source ./scripts/game

function imgNew {
  python ./jollybean/_utils/imgStrip.py ${*:2}
  declare -a outputImgs=($(echo $* | sed "s/png/c/g"))
  mv ${outputImgs[*]} $GAME/biome/seed/$IMAGE
}

function imgDel {
  echo hi;
}

function lower () {
  echo $1 | sed 's/.*/\L&/'
}

mainArg=$(lower $1)
case $mainArg in  
  game) gameExe ${*:2};;
  sys)  sysExe ${*};;
  gene) echo "what the del";;
  build) buildExe ${*:2};;
  *) echo "Command $mainArg not recognized.";;
esac

# TODO reimplement StripSet inside of imgStrip.py
# TODO add -g argument for game to specify game; if absent, check env vars for $GAME
# TODO make sure mv'ing imgStrip output to game dir works properly
# TODO make flexible add/rm functions that can handle any gene type
# TODO add function to check for existence of gene files and gene usage; call it in add/rm functions
# TODO if conflict exists, prompt user whether to replace it. 
# TODO add -y to auto-accept replacements of conflicts
# TODO add to/remove from headers
#sed -E "/$a/s/([0-Z ]+=\s*)(\*?[0-Z ]+)(\s*[;,\n].*)/\1$b\3/g" test 
