#!/bin/bash

TROVE=${HOME}/.jb

# Genes are gonna be externing all over the place.
# 1. Every gene ultimately boils down to:
#     a. MUTABLE: header + an array of key-pointer pairs
#     b. IMMUTABLE: header + pointer
# 2. And because they're pointers, game data is ultimately PLAIN DATA, easing development.
# 
#
# So let's spitball:
#
# IMMUTABLE CASE:
# ===============
# I can just write Cyan's battle stats straight off the bat without having to even think about genes.
# Then say I want to assign these stats to Cyan.
# I do jb gene add -t cyan -i cyanBattleStats

function add() {

}
