#include "body.h"

int main(int argc, char ** argv) {
  char *srcFilePath;
  Directory *cpDirP, *cmDirP;
  U32 origNColorPalettes, origNCollisionTypes, origNColormaps;

  // Verbose 
  U8 verbose = 0;
  if (!strcmp(argv[1], "-v")) {
    verbose = 1;
  }

  // Directories
  Error e = dirGet(&cpDirP, "ColorPalette", argc, verbose);
  if (!e) {
    e = dirGet(&cmDirP, "Colormap", argc, verbose);
  }
  if (!e) {
    origNColorPalettes = cpDirP->nEntries;
    origNColormaps = cmDirP->nEntries;
    cpDirP = cmDirP = NULL;
    origNColorPalettes = origNColormaps = 0;
  }

  // Write all the bodies.
  for (U32 i = 1 + verbose; !e && i < argc; ++i) {
    // Colormap and Color palette (autogenerated)
    e = getSrcFilePath(&srcFilePath, "Body/Graybody/Colormap/", argv[i]); 
    if (!e) {
      e = img(srcFilePath, cpDirP, cmDirP, verbose);
    }
    jbFree((void**) &srcFilePath);
    // Animation
    Animation *animP = NULL;
    if (!e) {
      e = getSrcFilePath(&srcFilePath, "Body/Graybody/Animation/", argv[i]); 
    }
    if (!e) {
      e = anim (srcFilePath, verbose, &animP);
    }
    jbFree((void**) &srcFilePath);
    // Collision
    if (!e) {
      e = getSrcFilePath(&srcFilePath, "Body/Graybody/Collision/", argv[i]); 
    }
    if (!e) {
      e = coll(srcFilePath, 0, animP, verbose);
    }
    jbFree((void**) &animP);
    jbFree((void**) &srcFilePath);
    // Genome
    // Seed
  }

  // Save the updated palette directory AFTER all updates are done.
  if (!e && cpDirP->nEntries != origNColorPalettes) {
    e = dirReplaceOriginal(cpDirP, "ColorPalette", verbose);
  }
  else if (verbose) {
    printf("\nNo new palettes to write.\n");
  }
  if (!e && cmDirP->nEntries != origNColormaps) {
    e = dirReplaceOriginal(cpDirP, "Colormap", verbose);
  }
  else if (verbose) {
    printf("\nNo new colormaps to write.\n");
  }

  return e;
}
